import BasePage, { Page, Locator, expect } from "./base/BasePage";
//generated by playwright-mcp
export class TodoPage extends BasePage {
  readonly newTodoInput: Locator;
  readonly todoItems: Locator;
  readonly todoCount: Locator;

  constructor(page: Page) {
    super(page);
    this.newTodoInput = this.page.getByPlaceholder("What needs to be done?");
    this.todoItems = this.page.locator(".todo-list li");
    this.todoCount = this.page.locator(".todo-count");
  }

  async goto(): Promise<void> {
    await this.page.goto("https://demo.playwright.dev/todomvc", {
      waitUntil: "domcontentloaded",
    });
  }

  async addTodo(title: string): Promise<void> {
    await this.newTodoInput.fill(title);
    await this.newTodoInput.press("Enter");
  }

  async addTodos(titles: string[]): Promise<void> {
    for (const title of titles) {
      await this.addTodo(title);
    }
  }

  async completeTodo(title: string): Promise<void> {
    await this.todoItems
      .filter({ hasText: title })
      .getByLabel("Toggle Todo")
      .check();
  }

  async completeAllTodos(): Promise<void> {
    const count = await this.todoItems.count();
    for (let i = 0; i < count; i++) {
      await this.todoItems.nth(i).getByLabel("Toggle Todo").check();
    }
  }

  async assertTodoCount(expected: number): Promise<void> {
    await expect(this.todoItems).toHaveCount(expected);
  }

  async assertTodoTitles(titles: string[]): Promise<void> {
    await expect(this.todoItems).toHaveText(titles);
  }

  async assertAllCompleted(): Promise<void> {
    const count = await this.todoItems.count();
    for (let i = 0; i < count; i++) {
      await expect(this.todoItems.nth(i)).toHaveClass(/completed/);
    }
    await expect(this.todoCount).toHaveText("0 items left");
  }
}
